# Workflow was stolen from Rojo. Thanks Rojo!

name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://doc.rust-lang.org/rustc/platform-support.html
        include:
          - host: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64

          - host: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

          - host: macos
            os: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64

          - host: macos
            os: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    env:
      BIN: zap
    steps:
      - uses: actions/checkout@v4

      - name: Get Version from Tag
        shell: bash
        run: |
          echo "PROJECT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Version is: ${{ env.PROJECT_VERSION }}"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          profile: minimal

      - name: Build Release
        run: cargo build --release --locked --verbose --target ${{ matrix.target }} --package cli
        env:
          CARGO_TARGET_DIR: output

      - name: Create Release Archive
        shell: bash
        run: |
          mkdir staging

          if [ "${{ matrix.host }}" = "windows" ]; then
            cp "output/${{ matrix.target }}/release/$BIN.exe" staging/
            cd staging
            7z a ../release.zip *
          else
            cp "output/${{ matrix.target }}/release/$BIN" staging/
            cd staging
            zip ../release.zip *
          fi

      - name: Upload Archive to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release.zip
          name: ${{ env.BIN }}-${{ env.PROJECT_VERSION }}-${{ matrix.label }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Archive to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN }}-${{ env.PROJECT_VERSION }}-${{ matrix.label }}.zip
          path: release.zip

  build-wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    env:
      BIN: zap
    steps:
      - uses: actions/checkout@v4

      - name: Get Version from Tag
        shell: bash
        run: |
          echo "PROJECT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "Version is: ${{ env.PROJECT_VERSION }}"

      - uses: oven-sh/setup-bun@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Release
        run: |
          wasm-pack build zap
          wasm-pack pack zap

      - name: Upload Archive to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: zap/pkg/${{ env.BIN }}-${{ env.PROJECT_VERSION }}.tgz
          name: ${{ env.BIN }}-${{ env.PROJECT_VERSION }}-wasm.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Archive to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BIN }}-${{ env.PROJECT_VERSION }}-wasm.tgz
          path: zap/pkg/${{ env.BIN }}-${{ env.PROJECT_VERSION }}.tgz
